/**
 * @const
 * @type {Object}
 */
export const CONNECTIONS_ACTION_TYPES = {
  SIGNIN: 'SIGNIN',
  SIGNOUT: 'SIGNOUT',
  ADD_CHAT_USER: 'ADD_CHAT_USER',
  JOIN_CHAT: 'JOIN_CHAT',
  LEAVE_CHAT: 'LEAVE_CHAT',
  OFFER: 'OFFER',
  ANSWER: 'ANSWER',
  CANDIDATE: 'CANDIDATE',
};
